name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.15.1] # or any other versions you want to test against
        mongodb-version: ["6.0", "7.0", "8.0"] # or any other version you want to test against

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: habit-tracker-test

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Schema
        run: npx prisma generate

      - name: Run unit tests
        run: npm test # or npm run test if that's your script
        env:
          POSTMARK_API_TOKEN: ${{ secrets.POSTMARK_API_TOKEN }}
          DATABASE_URL: "mongodb://localhost:27017/habit-tracker-test"
